environments:
  default:
    values:
    - jx-values.yaml
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: dev
    url: '{{ .Values | get "jxRequirements.cluster.chartRepository" " " }}'
releases:
- chart: bitnami/mysql
  version: 8.2.1
  name: mysql
  namespace: '{{ requiredEnv "PREVIEW_NAMESPACE" }}'
  wait: true
  values:
  - jx-values.yaml
  - mysql-values.yaml.gotmpl
- chart: '../charts/{{ requiredEnv "APP_NAME" }}'
  name: preview
  wait: true
  createNamespace: true
  namespace: '{{ requiredEnv "PREVIEW_NAMESPACE" }}'
  values:
  - jx-values.yaml
  - imagePullSecrets.yaml
  - values.yaml.gotmpl
  hooks:
  - events: ["presync"]
    showlogs: true
    command: "jx"
    args:
    - secret
    - copy
    - --create-namespace
    - --selector
    - "secret.jenkins-x.io/replica-source=true"
    - --to
    - '{{ requiredEnv "PREVIEW_NAMESPACE" }}'
