apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: conventional-commits
  labels:
    app.kubernetes.io/version: "0.2"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: "conventional-commits"
    tekton.dev/displayName: "conventional-commits"
spec:
  description: >-
    build
  workspaces:
    - name: source
      description: sources dir
  params:
    - name: MARDOWN_HEADER
      type: string
      description: header of comment
      default: "[Conventional Commits](https://www.conventionalcommits.org): **Check Failed** :cursing_face:"
    - name: PR_NUMBER
      type: string
      description: Pull Request Number to left comment
      default: ""
    - name: FAIL
      type: string
      description: Pull Request Number to left comment
      default: "false"
    - name: LINTER_IMAGE
      type: string
      description: image who scanning commits
      default: "aevea/commitsar:0.15.0"
  results:
    - name: report
      description: report of commits
    - name: mardown_report
      description: report of commits
    - name: passed
      description: is passed
  steps:
    - name: conventional-commits-check
      image: $(params.LINTER_IMAGE)
      workingDir: $(workspaces.source.path)
      script: |
        if commitsar > $(results.report.path); then
          echo -n "true" > $(results.passed.path)
        else
          echo -n "false" > $(results.passed.path)
        fi
        cat $(results.report.path)
    - name: conventional-commits-prepare-report
      image: $(params.LINTER_IMAGE)
      workingDir: $(workspaces.source.path)
      script: |
        echo "=== Building mardown"
        export COLUMNS=$(cat $(results.report.path) | grep "|" | awk -F"|" '{printf "%s | %s | %s", $2, $3, $4;} {print ""}' | grep -v -e '^[[:space:]]*$' | tail -n +2 | grep '[[:alnum:]]')
        echo -e "$(params.MARDOWN_HEADER) \n HASH | ERROR | MSG \n --|--|-- \n $COLUMNS" > $(results.mardown_report.path)
    - name: conventional-commits-comment
      image: gcr.io/jenkinsxio/jx-boot:3.1.43
      workingDir: $(workspaces.source.path)
      script: |
        if [ -z "$(params.PR_NUMBER)" ]; then
            echo "No PR_NUMBER parameter provider, skipping commet."
          else
            if ! "$(cat $(results.passed.path))" ; then
              jx gitops pr comment --pr="$(params.PR_NUMBER)" --comment="$(cat $(results.mardown_report.path))"
            fi
        fi
    - name: conventional-commits-final
      image: gcr.io/jenkinsxio/jx-boot:3.1.43
      workingDir: $(workspaces.source.path)
      script: |-
        if "$(params.FAIL)" ; then
          if ! "$(cat $(results.passed.path))" ; then
            exit 1
          fi
        fi
