apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gradle-build
  labels:
    app.kubernetes.io/version: "0.2"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: "gradle"
    tekton.dev/displayName: "gradle"
spec:
  description: >-
    build
  workspaces:
    - name: source
      description: sources dir
  params:
    - name: IMAGE
      description: gradle image with jdk
      type: string
      default: "gradle:6.3.0-jdk11"
    - name: JAVA_OPTIONS
      default: "-Xms10m -Xmx192m"
    - name: GRADLE_PVC
      description: "gradle home pvc name"
      default: "gradle-home"
    - name: ARGS
      description: gradle exctra args
      type: array
      default:
        - clean
        - build
        - --no-daemon
  volumes:
    - name: gradle-home-cache
      persistentVolumeClaim:
        claimName: "$(params.GRADLE_PVC)"
  steps:
    - name: build
      image: $(params.IMAGE)
      imagePullPolicy: IfNotPresent
      workingDir: $(workspaces.source.path)
      command:
        - gradle
      args:
        - "$(params.ARGS[*])"
        - "-Dgradle.user.home=/.gradle"
      env:
        - name: _JAVA_OPTIONS
          value: "$(params.JAVA_OPTIONS)"
      volumeMounts:
        - name: gradle-home-cache
          mountPath: /.gradle

