apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: node-build
  labels:
    app.kubernetes.io/version: "0.2"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: "node"
    tekton.dev/displayName: "node-build"
spec:
  description: >-
    build
  workspaces:
    - name: source
      description: sources dir
  params:
    - name: IMAGE
      description: node image
      type: string
      default: "node:12.19.0-slim"
  steps:
    - name: install
      image: $(params.IMAGE)
      workingDir: $(workspaces.source.path)
      command:
        - npm
      args:
        - install

    - name: test
      image: $(params.IMAGE)
      workingDir: $(workspaces.source.path)
      script: |
        CI=true DISPLAY=:99 npm test

    - name: build-prod
      image: $(params.IMAGE)
      workingDir: $(workspaces.source.path)
      command:
        - npm
      args:
        - run
        - build-prod

