apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: python-build-with-coverage
  labels:
    app.kubernetes.io/version: "0.2"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: "node"
    tekton.dev/displayName: "node-build"
spec:
  description: >-
    build
  workspaces:
    - name: source
      description: sources dir
  steps:
    - name: build
      image: python:3.7
      imagePullPolicy: IfNotPresent
      workingDir: $(workspaces.source.path)
      script: |
        pip install --no-cache-dir -r requirements.txt
        coverage erase
        coverage run -m unittest
        coverage xml -i

