apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    lighthouse.jenkins-x.io/loadFileRefs: .*
    lighthouse.jenkins-x.io/prependStepsURL: https://raw.githubusercontent.com/jenkins-x/jx3-pipeline-catalog/005e78cf69b643862344397a635736a51dd1bd89/tasks/git-clone/git-clone.yaml
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    workspaces:
      - name: source
        description: where sources is cloned
    params:
      - default: master
        description: git revision to checkout (branch, tag, sha, ref…)
        name: revision
        type: string
      - name: LARGE_REPORTS_IMAGE
        default: gcr.io/sdlc-286111/mood-feed-test:latest
        description: image with large reports sources
        type: string
      - name: PULL_NUMBER
        default: ""
      - name: PULL_PULL_REF
        default: ""
      - name: PULL_PULL_SHA
        default: ""
    tasks:

#      - name: large-test-prepare-and-check
#        workspaces:
#          - name: source
#            workspace: source
#        taskRef:
#          name: large-tests-prepare
#        params:
#          - name: REPORTS_PVC_NAME
#            value: "large-test"

      - name: from-build-pack
        workspaces:
          - name: source
            workspace: source
#        runAfter:
#          - "large-test-prepare-and-check"
        params:
          - name: revision
            value: $(params.revision)
        taskSpec:
          workspaces:
            - name: source
              mountPath: /workspace
              description: sources
          params:
            - default: master
              description: git revision to checkout (branch, tag, sha, ref…)
              name: revision
              type: string
          stepTemplate:
            env:
              - name: PIPELINE_KIND
                value: release
              - name: JX_BATCH_MODE
                value: "true"
              - name: VERSION
                value: $(inputs.params.version)
            name: ""
            resources:
              requests:
                cpu: 400m
                memory: 512Mi
            workingDir: /workspace/source
          steps:
            - name: git-prepare
              image: gcr.io/jenkinsxio/jx-cli:latest
              script: |
                #!/usr/bin/env bash
                git config --global --add user.name ${GIT_AUTHOR_NAME:-jenkins-x-bot}
                git config --global --add user.email ${GIT_AUTHOR_EMAIL:-jenkins-x@googlegroups.com}
                git config --global credential.helper store

            - args:
                - pr
              command:
                - make
              image: gcr.io/jenkinsxio/jx-cli:3.0.705
              name: make-pr

#      - name: large-test-execute
#        workspaces:
#          - name: source
#            workspace: source
#        runAfter:
#          - "from-build-pack"
#        taskRef:
#          name: large-tests-execute
#        params:
#          - name: LARGE_REPORTS_IMAGE
#            value: "gcr.io/sdlc-286111/mood-feed-test:latest"
#          - name: REPORTS_PVC_NAME
#            value: "large-test"
#          - name: SLACK_SECRET
#            value: "slack"
#          - name: APP_URL_STAGING
#            value: "http://mood-feed-frontend-jx-staging.35.195.151.253.nip.io"
#          - name: APP_URL_PRODUCTION
#            value: "http://mood-feed-frontend-jx-production.35.195.151.253.nip.io"
#          - name: ENVIRONMENTS_TO_TEST
#            value: $(tasks.large-test-prepare-and-check.results.env_to_test)

  podTemplate:
    imagePullSecrets:
      - name: "docker-registry-auth"
  serviceAccountName: tekton-build-bot
  timeout: 30m
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi