apiVersion: config.lighthouse.jenkins-x.io/v1alpha1
kind: TriggerConfig
spec:
  presubmits:
    - name: large-test-check
      context: "large-test-check"
      always_run: false
      optional: true
      trigger: (?m)^/test( all| ltc),?(s+|$)
      rerun_command: /test ltc
      source: "large-tests-check-pipelinerun.yaml"
  postsubmits:

