environments:
  default:
    values:
      - jx-values.yaml
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: dev
    url: '{{ .Values | get "jxRequirements.cluster.chartRepository" " " }}'
releases:
#- chart: dev/mood-feed-backend
#  name: mood-feed-backend
#  wait: true
#  namespace: '{{ requiredEnv "PREVIEW_NAMESPACE" }}'
#  values:
#    - backend-values.yaml
#    - imagePullSecrets.yaml
#- chart: bitnami/mysql
#  version: 8.2.1
#  name: mysql
#  namespace: '{{ requiredEnv "PREVIEW_NAMESPACE" }}'
#  wait: true
#  values:
#    - mysql-values.yaml.gotmpl
#    - imagePullSecrets.yaml
#    - jx-values.yaml
- chart: '../charts/{{ requiredEnv "APP_NAME" }}'
  name: preview
  wait: true
  createNamespace: true
  namespace: '{{ requiredEnv "PREVIEW_NAMESPACE" }}'
  values:
  - values.yaml.gotmpl
  - jx-values.yaml
  - imagePullSecrets.yaml
  hooks:
  - events: ["presync"]
    showlogs: true
    command: "jx"
    args:
    - secret
    - copy
    - --create-namespace
    - --selector
    - "secret.jenkins-x.io/replica-source=true"
    - --to
    - '{{ requiredEnv "PREVIEW_NAMESPACE" }}'
